version: '3.7'
services:
  #DB
  postgres:
    container_name: postgres_container
    image: bitnami/postgresql
    environment:
      POSTGRESQL_PGAUDIT_LOG: READ,WRITE
      POSTGRESQL_LOG_HOSTNAME: true
      POSTGRESQL_REPLICATION_MODE: master
      POSTGRESQL_REPLICATION_USER: repl_user
      POSTGRESQL_REPLICATION_PASSWORD: repl_password
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_DATABASE: back
    volumes:
      - pgdata:/bitnami/postgresql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./sql:/db_data
    networks:
      - postgres_network

  postgres_slave:
    container_name: postgres_slave_container
    image: bitnami/postgresql
    environment:
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_MASTER_HOST: postgres
      POSTGRESQL_PGAUDIT_LOG: READ
      POSTGRESQL_LOG_HOSTNAME: true
      POSTGRESQL_REPLICATION_MODE: slave
      POSTGRESQL_REPLICATION_USER: repl_user
      POSTGRESQL_REPLICATION_PASSWORD: repl_password
      POSTGRESQL_MASTER_PORT_NUMBER: 5432
      ALLOW_EMPTY_PASSWORD: yes
    depends_on:
      - postgres
    networks:
      - postgres_network  
  #WEBAPP
  webapp1:
    container_name: webapp_container1
    restart: always
    depends_on:
      - postgres
    build:
      context: .
      dockerfile:  Dockerfile
    environment:
      - PG_USER=postgres
      - PG_HOST=postgres
      - PG_PASSWORD=postgres
      - PG_DATABASE=back
      - PG_PORT=5432
    volumes:
      - ./:/app
    networks:
      - postgres_network
      - nginx_network

  webapp2:
    container_name: webapp_container2
    restart: always
    depends_on:
      - postgres
    build:
      context: .
      dockerfile:  Dockerfile
    environment:
      - PG_USER=postgres
      - PG_HOST=postgres
      - PG_PASSWORD=postgres
      - PG_DATABASE=back
      - PG_PORT=5432
    volumes:
      - ./:/app
    networks:
      - postgres_network
      - nginx_network

  webapp3:
    container_name: webapp_container3
    restart: always
    depends_on:
      - postgres
    build:
      context: .
      dockerfile:  Dockerfile
    environment:
      - PG_USER=postgres
      - PG_HOST=postgres
      - PG_PASSWORD=postgres
      - PG_DATABASE=back
      - PG_PORT=5432
    volumes:
      - ./:/app
    networks:
      - postgres_network
      - nginx_network
  
  webapp_mirror:
    container_name: webapp_mirror_container
    restart: always
    depends_on:
      - postgres
    build:
      context: .
      dockerfile:  Dockerfile
    environment:
      - PG_USER=postgres
      - PG_HOST=postgres_slave
      - PG_PASSWORD=postgres
      - PG_DATABASE=back
      - PG_PORT=5432
    volumes:
      - ./:/app
    networks:
      - postgres_network
      - nginx_network

  #PG ADMIN
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest
    restart: always
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - postgres_network
      - nginx_network
  #NGINX
  nginx:
    image: 'byjg/nginx-extras'
    container_name: nginx_container
    depends_on:
      - pgadmin
      - webapp1
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ./README.md:/static/documentation/README.md
      - ./static/img/:/static/documentation/img/
      - ./benchmark/img/:/static/benchmark/img/
      - ./benchmark/bench.md:/static/benchmark/bench.md
      - ./static:/static
    ports:
      - "3000:3000"
      - "80:80"
      - "443:443"
      - "81:81"
    networks:
      - nginx_network

volumes:
  pgadmin-data:
  pgdata:
    driver: local

networks:
  postgres_network:
    driver: bridge
  nginx_network:
    driver: bridge
